<div class="home">
    <h1>
        HOME
    </h1>
    <p>
        <a href="/admin/">Admin functions</a><br>
        <a href="/home/roles">View roles (52.3.1)</a><br>
        <a href="/home/logs">Manage a log (52.5.1)</a><br>
        <a href="/admin/vkcontent">vkcontent</a><br>
        <a href="/admin/<?=(!isset($_SESSION['isauth']))?'login\">Log me in (52.2.1)':'logout\">Log me out'; ?>.</a>
    </p>
</div>